apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - policy-openshift-gitops-operator.yaml
  - policy-openshift-gitops-policygenerator.yaml
  - placement.yaml
  - placementbinding.yaml
