---
apiVersion: v1
kind: Namespace
metadata:
  name: policiesa
  labels:
    demo.example.com/part-of: policy-dependency-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: policiesb
  labels:
    demo.example.com/part-of: policy-dependency-demo
