---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-dependency-demo-a
  namespace: openshift-gitops
spec:
  project: policy-dependency-demo
  destination:
    namespace: policiesa
    server: https://kubernetes.default.svc
  source:
    path: policiesa
    repoURL: https://github.com/ch-stark/policydependencydemo
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-dependency-demo-b
  namespace: openshift-gitops
spec:
  project: policy-dependency-demo
  destination:
    namespace: policiesb
    server: https://kubernetes.default.svc
  source:
    path: policiesb
    repoURL: https://github.com/ch-stark/policydependencydemo
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: true
